config/routes.rb
ScreeningLog::Application.routes.draw do
  resources :screenings
  resources :directors
  resources :films

  root 'screenings#recent'

  get 'screenings/year/:year' => 'screenings#year', as: 'screening_year'

  get 'films/year/:year' => 'films#year', as: 'year'
  get 'films-by-rating/:rating' => 'films#rating', as: 'rating'
  get 'films/year/:year/:type' => 'films#year', as: 'year_grid'
  get '/recent' => 'screenings#recent', as: 'recent'

  get '/search' => 'films#search'

  get '/top-tens' => 'films#toptens', as: 'top_tens'
  get '/decades' => 'films#decades', as: 'decades'
  get '/top-100' => 'films#top100', as: 'top_100'
  get '/worst' => 'films#worst', as: 'worst'
  get '/top-100/:type' => 'films#top100', as: 'top_100_grid'
  get '/no-directors' => 'films#no_directors', as: 'no_directors'

  get '/visualized' => 'screenings#visualized', as: 'visualized'

  get '/all' => "films#all", as: 'all'

  get '/no-images' => 'films#no_images', as: 'no_image'

end

app/models/screening.rb
class Screening < ActiveRecord::Base
  belongs_to :film
  has_many :directors, through: :film

  validates_numericality_of :rating, :less_than_or_equal_to => 100, :greater_than_or_equal_to => 0

  def week
    self.date.strftime('%W')
  end

  def year
    self.date.strftime('%Y')
  end

  def rating_tier
    case self.rating.to_i
      when 2010..2019 then "2010s"
      when 2000..2009 then "2000s"
      when 1990..1999 then "1990s"
      when 1980..1989 then "1980s"
      when 1970..1979 then "1970s"
      when 1960..1969 then "1960s"
      when 1950..1959 then "1950s"
      when 1940..1949 then "1940s"
      when 1930..1939 then "1930s"
      when 1920..1929 then "1920s"
      when 1910..1919 then "1910s"
      when 1900..1909 then "1900s"
      when 1800..1899 then "1800s"
    end
  end

end

app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController
  before_action :set_screening, only: [:show, :edit, :update, :destroy]

  # GET /screenings
  # GET /screenings.json
  def index
    @screenings = Screening.all.includes(:film).order(date: :asc).paginate(:page => params[:page], :per_page => 30)
  end

  def recent
    @screenings = Screening.all.includes(film: [:directors]).order(date: :desc).paginate(:page => (params[:page] || 1),
                                                            :per_page => (params[:count] || 60))
  end

  def year
    @screenings = Screening.all.includes(:film).order(date: :asc).where("date LIKE ?", params[:year] + "%")
    @year = params[:year].to_i
    @next_year = @year + 1 if @year < Time.now.year
    @previous_year = @year - 1
  end

  def visualized
    @screenings = Screening.all

    @one = @screenings.where("rating >= 1 AND rating <= 10").count()
    @two = @screenings.where("rating >= 11 AND rating <= 20").count()
    @three = @screenings.where("rating >= 21 AND rating <= 30").count()
    @four = @screenings.where("rating >= 31 AND rating <= 40").count()
    @five = @screenings.where("rating >= 41 AND rating <= 50").count()
    @six = @screenings.where("rating >= 51 AND rating <= 60").count()
    @seven = @screenings.where("rating >= 61 AND rating <= 70").count()
    @eight = @screenings.where("rating >= 71 AND rating <= 80").count()
    @nine = @screenings.where("rating >= 81 AND rating <= 90").count()
    @ten = @screenings.where("rating >= 91 AND rating <= 100").count()

    @ratings = [ @one, @two, @three, @four, @five, @six, @seven, @eight, @nine, @ten]
    @max_rating = @ratings.max

    @films = Film.all
    @decades = @films.group_by { |t| t.decade }

    @directors = Director.joins(:films).select("directors.*, count(films.id) as fcount").group("directors.id").order("fcount DESC").limit(30)
    @most_watched_films = Film.joins(:screenings).select("films.*, count(screenings.id) as scount").group("films.id").order("scount DESC").limit(15)
  end

  # GET /screenings/1
  # GET /screenings/1.json
  def show
  end

  # GET /screenings/new
  def new
    @screening = Screening.new
  end

  # GET /screenings/1/edit
  def edit
  end

  # POST /screenings
  # POST /screenings.json
  def create
    @screening = Screening.new(screening_params)

    respond_to do |format|
      if @screening.save
        format.html { redirect_to @screening, notice: 'Screening was successfully created.' }
        format.json { render action: 'show', status: :created, location: @screening }
      else
        format.html { render action: 'new' }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screenings/1
  # PATCH/PUT /screenings/1.json
  def update
    respond_to do |format|
      if @screening.update(screening_params)
        format.html { redirect_to @screening, notice: 'Screening was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenings/1
  # DELETE /screenings/1.json
  def destroy
    @screening.destroy
    respond_to do |format|
      format.html { redirect_to screenings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screening
      @screening = Screening.find(params[:id], :include => [:film])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screening_params
      params.require(:screening).permit(:date, :rating, :film_id)
    end
end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/views/screenings/_form.html.erb
<%= form_for(@screening) do |f| %>
  <% if @screening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screening.errors.count, "error") %> prohibited this screening from being saved:</h2>

      <ul>
      <% @screening.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :film_id %><br />
    <%= f.collection_select(:film_id, Film.find(:all), :id, :title, {:prompt => true}, :class => "chosen-select") %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <div class="ratings">
    <p>
    100-90: Masterpiece, or damn close. Very rare.<br>
 89-80: Fanthefucktastic. Near-lock for my year-end top 10 list.<br>
 79-70: Definitely something special. Do not miss. Likely list contender.<br>
 69-60: Very good, but also flawed or missing some crucial element.<br>
 59-50: Didn’t quite work for me, but has many redeeming qualities.<br>
 49-40: Demerits clearly outweigh merits.<br>
 39-30: I really did not enjoy this picture, but talent was involved.<br>
 29-20: When will this fucking picture end. When.<br>
 19-10: Outright fiasco and/or unwatchably boring.<br>
   9-0: One of the worst movies I’ve ever seen. Very rare.
 </p>
  </div>
<% end %>

app/views/screenings/edit.html.erb
<h1>Editing screening</h1>

<%= render 'form' %>

<%= link_to 'Show', @screening %> |
<%= link_to 'Back', screenings_path %>

app/views/screenings/index.html.erb
<% title "Screenings - Screening Log" %>

<div class="screening__index">

  <h1>Screenings <small><%= @screenings.count() %></small></h1>

  <%= link_to 'New Screening', new_screening_path, :class => "button" %>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Film</th>
        <th>Rating</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @screenings.each do |screening| %>
      <tr>
        <td><%= link_to screening.date.strftime("%Y-%m-%d"), screening, :class => "screening-date" %></td>
        <td <%= ' class="repeat"' if screening.film.screenings.size > 1 and (screening.film.screenings.first != screening) %>><%= link_to screening.film.title, screening.film %> (<%=h screening.film.year %>, <%= display_directors(screening.film) %>)</td>
        <td><%= screening.rating %></td>
        <td>
          <%= link_to edit_screening_path(screening), :class => "action-link" do %>
            <%= fa_icon "pencil" %>
          <% end %>
        </td>
        <td>
          <%= link_to screening, method: :delete, data: { confirm: 'Are you sure?' }, :class => "action-link" do %>
            <%= fa_icon "times" %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @screenings %>

</div>

app/views/screenings/new.html.erb
<h1>New screening</h1>

<%= render 'form' %>

<%= link_to 'Back', screenings_path %>

app/views/screenings/recent.html.erb
<% title "Screenings - Screening Log" %>

<h1>Recent</h1>

<div class="screening__recent">

  <% @screenings.each do |screening| %>

  <div class="module">
    <%= link_to screening.film do %>
    <%= image_tag image_path(screening.film.image.url(:thumb))  %>
    <% end %>

    <div class="module__info">
      <div class="inner-cell"><div class="center-cell">
        <%= link_to screening.film.title, screening.film, :class => "module__film-title" %>
        <span class="module__meta">(<%=h screening.film.year %>, <%= display_directors(screening.film) %>)<br>
          <span class="module__rating"><%= star_rating(screening.rating) %> / <%= letter_grade(screening.rating) %></span>
        </span></div>
      </div>
    </div>
  </div>
  <% end %>

</div>

<%= will_paginate @films %>

app/views/screenings/show.html.erb
<p class="notice"><%= notice %></p>


<h1><%= link_to @screening.film.title, @screening.film %> (<%=h @screening.film.year %>, <%= display_directors(@screening.film) %>) <%=h @screening.rating %></h1>

<p>
  <strong>Date:</strong>
  <%# TODO: link to screening year page for easy navigation %>
  <%= link_to @screening.date, "/screenings/year/#{@screening.date.year}##{@screening.id}", :class => "action-link" %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @screening.rating %>
</p>

<%= link_to 'Edit', edit_screening_path(@screening) %> |
<%= link_to 'Back', screenings_path %>

app/views/screenings/visualized.html.erb
<% title "Visualized - Screening Log" %>

<%# TO DO: Refactor into virtual attribute %>
<div class="info-graphics">
    <div class="rating-spread">
        <h2>Rating Distribution</h2>

        <table class="visualization-table">
            <tr>
                <td class="visualization-range"><h3>1-10</h3></td>
                <td class="visualization-count"><%= @one %></td>
                <td><div class="bar" style="width: <%= ( @one.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
            <tr>
                <td class="visualization-range"><h3>11-20</h3></td>
                <td class="visualization-count"><%= @two %></td>
                <td><div class="bar" style="width: <%= ( @two.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
            <tr>
                <td class="visualization-range"><h3>21-30</h3></td>
                <td class="visualization-count"><%= @three %></td>
                <td><div class="bar" style="width: <%= ( @three.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
            <tr>
                <td class="visualization-range"><h3>31-40</h3></td>
                <td class="visualization-count"><%= @four %></td>
                <td><div class="bar" style="width: <%= ( @four.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
            <tr>
                <td class="visualization-range"><h3>41-50</h3></td>
                <td class="visualization-count"><%= @five %></td>
                <td><div class="bar" style="width: <%= ( @five.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
            <tr>
                <td class="visualization-range"><h3>51-60</h3></td>
                <td class="visualization-count"><%= @six %></td>
                <td><div class="bar" style="width: <%= ( @six.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
            <tr>
                <td class="visualization-range"><h3>61-70</h3></td>
                <td class="visualization-count"><%= @seven %></td>
                <td><div class="bar" style="width: <%= ( @seven.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
            <tr>
                <td class="visualization-range"><h3>71-80</h3></td>
                <td class="visualization-count"><%= @eight %></td>
                <td><div class="bar" style="width: <%= ( @eight.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
            <tr>
                <td class="visualization-range"><h3>81-90</h3></td>
                <td class="visualization-count"><%= @nine %></td>
                <td><div class="bar" style="width: <%= ( @nine.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
            <tr>
                <td class="visualization-range"><h3>91-100</h3></td>
                <td class="visualization-count"><%= @ten %></td>
                <td><div class="bar" style="width: <%= ( @ten.to_f / @max_rating ) * 100 %>%">&nbsp;</div></td>
            </tr>
        </table>


    </div>


    <div class="most-watched-directors">

        <h2>Most Watched Directors</h2>

        <table class="visualization-table">

        <% first = @directors.first.films.count %>
        <% @directors.each_with_index do |director, index| %>
        <tr>
            <td class="most-watched-directors__director">
            <%= link_to director do %>
            <h3><%= index + 1 %>. <%= director.full_name %></h3>
            <% end %>
            </td>
            <td class="visualization-count"><%= director.films.count %></td>
            <td class="most-watched-directors__bar">
                    <div class="bar" style="width: <%= ( director.films.count.to_f / 22 ) * 100 %>%">
                        &nbsp;<%#= director.films.count %>
                    </div>
            </td>

        </tr>
        <% end %>
        </table>

    </div>


    <div class="films-by-decade">

        <h2>Films by Decade</h2>
        <table class="visualization-table">

        <% @decades.sort.reverse.each do |decade, films|  %>
        <tr>
          <td style="width: 10%;"><h3><%= decade %></h3></td>
          <td class="visualization-count">  <%= films.count %></td>
          <td>
          <div class="bar" style="width:100%; max-width: <%= films.count * 1.3 %>px" title="<%= films.count %>">
            &nbsp;
          </div>
         </td>
        </tr>
        <% end -%>

        </table>

    </div>


</div>

app/views/screenings/year.html.erb
<% title "#{@year} - Screenings - Screening Log" %>

<div class="screening__index">

  <h1>Screenings: <%= @year %> <small><%= @screenings.count %></small></h1>

  <table id="screenings">
    <thead>
      <tr>
        <th></th>
        <th>Date</th>
        <th>Film</th>
        <th>Rating</th>
      </tr>
    </thead>

    <tbody>
      <% @screenings.each_with_index do |screening, index| %>
        <tr id="<%= screening.id %>">
          <td><%= index + 1 %>.</td>
          <td><%= link_to screening.date.strftime("%Y-%m-%d"), screening, :class => "screening-date" %></td>
          <td class="film-cell<%= ' repeat' if screening.film.screenings.size > 1 and (screening.film.screenings.first != screening) %>"><%= link_to screening.film.title, screening.film %> (<%= link_to screening.film.year, year_path(screening.film.year), :class => "director-link" %>, <%= screening.film.directors.map{|d|  link_to(d.try(:full_name), d, :class => "director-link")}.join(", ").html_safe %>)</td>
          <td><%= screening.rating %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <nav class="year-nav">
    <%= link_to "&larr; #{@previous_year}".html_safe, screening_year_path(@previous_year) %>
   <% if @next_year %>
    <%= link_to "#{@next_year} &rarr;".html_safe, screening_year_path(@next_year) %>
   <% end %>
 </nav>



</div>