config/routes.rb
ScreeningLog::Application.routes.draw do
  resources :screenings
  resources :directors
  resources :films

  root 'screenings#recent'

  get 'screenings/year/:year' => 'screenings#year', as: 'screening_year'

  get 'films/year/:year' => 'films#year', as: 'year'
  get 'films-by-rating/:rating' => 'films#rating', as: 'rating'
  get 'films/year/:year/:type' => 'films#year', as: 'year_grid'
  get '/recent' => 'screenings#recent', as: 'recent'

  get '/search' => 'films#search'

  get '/top-tens' => 'films#toptens', as: 'top_tens'
  get '/decades' => 'films#decades', as: 'decades'
  get '/top-100' => 'films#top100', as: 'top_100'
  get '/worst' => 'films#worst', as: 'worst'
  get '/top-100/:type' => 'films#top100', as: 'top_100_grid'
  get '/no-directors' => 'films#no_directors', as: 'no_directors'

  get '/visualized' => 'screenings#visualized', as: 'visualized'

  get '/all' => "films#all", as: 'all'

  get '/no-images' => 'films#no_images', as: 'no_image'

end

app/models/director.rb
class Director < ActiveRecord::Base
  default_scope order('last_name ASC')
  has_and_belongs_to_many :films

  validates :last_name, :presence => true

  extend FriendlyId
  friendly_id :full_name, use: [:slugged, :history]

  def full_name
    [first_name, middle_name, last_name].reject{|i| i.empty?}.compact.join(" ")
  end

  def should_generate_new_friendly_id?
    last_name_changed?
    first_name_changed?
  end

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]

  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all.paginate(:page => params[:page], :per_page => 50)

    # respond_to do |format|
    #   format.html
    #   format.json { render :json => @directors.map(&:attributes) }
    # end
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
    @films = @director.films.includes(:screenings).order('year ASC')
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render action: 'show', status: :created, location: @director }
      else
        format.html { render action: 'new' }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, :page => params[:page], notice: 'Director was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, :page => params[:page] }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:first_name, :middle_name, :last_name)
    end
  end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_for(@director) do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field last_name">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<% title "Edit Director - Screening Log" %>


<h1>Editing director</h1>

<%= render 'form' %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

app/views/directors/index.html.erb
<% title "Directors - Screening Log" %>

<div class="directors__index">

  <h1>Directors <small><%= @directors.count %></small></h1>

  <%= link_to 'New Director', new_director_path, :class => "button" %>

  <table>
    <thead>
      <tr>
        <th>Full name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @directors.each do |director| %>
      <tr>
        <td><%= link_to director.full_name, director %></td>
        <td><%= link_to edit_director_path(director), :class => "action-link" do %><%= fa_icon "pencil" %><% end %></td>
        <td><%= link_to director, method: :delete, data: { confirm: 'Are you sure?' }, :class => "action-link" do %><%= fa_icon "times" %><% end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @directors %>

</div>

app/views/directors/new.html.erb
<% title "New Director - Screening Log" %>

<h1>New director</h1>

<%= render 'form' %>

<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<% title "#{@director.full_name} - Directors - Screening Log" %>
<article class="director">

    <% if notice %>
        <p class="notice"><%= notice %></p>
    <% end %>

    <h1 class="director-name"><%= @director.full_name %> <small><%= @films.count %></small></h1>

    <nav class="director-action-nav">
        <%= link_to edit_director_path(@director), :class => 'action-link' do %><%= fa_icon "pencil", text: "Edit" %><% end %> &nbsp;&nbsp;
        <%= link_to @director, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'action-link' do %><%= fa_icon "times", text: "Delete" %><% end %>
    </nav>

    <ul class="film-list">
        <% @films.each do |film| %>
        <li>
            <%= link_to image_tag(film.image.url(:thumb)), film %>
            <div class="film-list__info">
            <%= link_to film.title, film %> (<%= film.year %>)
            <small><%= film.last_rating %> / <%= star_rating(film.last_rating) %></small>
            </div>
        </li>
        <% end %>
    </ul>

    <div class="rating-graph">
        <ul>
            <% @films.each_with_index do |film, index| %>
            <li style="left: <%= index * 31 %>px; height: <%= film.last_rating %>px;">
                <small><%= film.last_rating %></small>
            </li>
            <% end %>
        </ul>
    </div>

    <p>Average Rating: <%= (@films.collect(&:last_rating).sum.to_f/@films.length).round if @films.length > 0 %></p>


</article>