config/routes.rb
ScreeningLog::Application.routes.draw do
  resources :screenings
  resources :directors
  resources :films

  root 'screenings#recent'

  get 'screenings/year/:year' => 'screenings#year', as: 'screening_year'

  get 'films/year/:year' => 'films#year', as: 'year'
  get 'films-by-rating/:rating' => 'films#rating', as: 'rating'
  get 'films/year/:year/:type' => 'films#year', as: 'year_grid'
  get '/recent' => 'screenings#recent', as: 'recent'

  get '/search' => 'films#search'

  get '/top-tens' => 'films#toptens', as: 'top_tens'
  get '/decades' => 'films#decades', as: 'decades'
  get '/top-100' => 'films#top100', as: 'top_100'
  get '/worst' => 'films#worst', as: 'worst'
  get '/top-100/:type' => 'films#top100', as: 'top_100_grid'
  get '/no-directors' => 'films#no_directors', as: 'no_directors'

  get '/visualized' => 'screenings#visualized', as: 'visualized'

  get '/all' => "films#all", as: 'all'

  get '/no-images' => 'films#no_images', as: 'no_image'

end

app/models/film.rb
class Film < ActiveRecord::Base
  has_and_belongs_to_many :directors
  has_many :screenings, :dependent => :destroy

  validates :title, :year, :presence => true
  validates_length_of :year, :within => 4..4

  has_attached_file :image,
                    :styles => {
                      :large => "600x400>",
                      :thumb => "300x196#"
                    },
                    :default_url => "/images/:style/missing.png"


  scope :find_by_year, ->(year) { where(:year => year) }
  scope :favorites, -> { includes(:screenings).where("screenings.rating > ?", "59") }
  # scope :favorites, :include => :screenings, :conditions => ["screenings.rating > 59"]
  # scope :ordered, lambda { |order| { :order => order || 'title ASC' }}

  # default_scope { includes(:directors) }


  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :title,
      [:title, :year],
    ]
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def thumb_url
    image.url(:thumb)
  end

  def last_rating
    if screenings.size > 0
      screenings.sort{|a, b| b.date <=> a.date}.first.rating
    else
      0
    end
  end

  def recently_seen?
    if screenings.size > 0
      screenings.sort{|a, b| b.date <=> a.date}.first.date > 1.month.ago
    else
      false
    end
  end

  def self.top_100
    all_films = Film.all.includes(:screenings)
    all_films.sort do |a, b|
      if a.last_rating == b.last_rating
        b.title <=> a.title
      else
        a.last_rating <=> b.last_rating
      end
    end.reverse[0..249]
  end

  def self.worst
    all_films = Film.find(:all, :include => [:screenings])
    all_films.sort do |a, b|
      if a.last_rating == b.last_rating
        b.title <=> a.title
      else
        a.last_rating <=> b.last_rating
      end
    end[0..99]
  end

  def self.search(search)
    if search
      Film.all.where('lower(title) LIKE :q', {:q => "%#{search}%"})
    else
      find(:all)
    end
  end

  def decade
    case self.year.to_i
      when 2010..2019 then "2010s"
      when 2000..2009 then "2000s"
      when 1990..1999 then "1990s"
      when 1980..1989 then "1980s"
      when 1970..1979 then "1970s"
      when 1960..1969 then "1960s"
      when 1950..1959 then "1950s"
      when 1940..1949 then "1940s"
      when 1930..1939 then "1930s"
      when 1920..1929 then "1920s"
      when 1910..1919 then "1910s"
      when 1900..1909 then "1900s"
      when 1800..1899 then "1800s"
    end
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all.includes(:directors).paginate(:page => params[:page], :per_page => 30)
  end

  def all
    @films = Film.all
  end

  def no_images

    @films = Film.where({:image_file_size => nil}).paginate(:page => params[:page], :per_page => 30).reverse_order

    render :action => "index"
  end


  def search
    @films = Film.includes(:directors).search(params[:search]).paginate(:page => (params[:page] || 1),
                                       :per_page => (params[:count] || 60))
    render :action => "index"
  end

  def year
    @year = params[:year].to_i
    @next_year = @year + 1 if @year < Time.now.year
    @previous_year = @year - 1

    @films = Film.includes(:screenings, :directors).find_by_year(params[:year])
    sort_to_most_recent_rating
  end

  def toptens
    @films = Film.joins(:screenings).favorites.all(:include => [:screenings, :directors], :order => "screenings.rating DESC")
    sort_to_most_recent_rating
    @film_years = @films.group_by { |t| t.year }
  end

  def top100
    @films = Film.top_100
  end

  def worst
    @films = Film.worst
    render :action => "top100"
  end

  def decades
    @films = Film.joins(:screenings).favorites.all(:include => [:screenings], :order => "screenings.rating DESC")
    sort_to_most_recent_rating
    @decades = @films.group_by { |t| t.decade }
  end

  def no_directors
    @films = Film.all.select {|f| f.directors.count == 0 }
    render :action => 'year'
  end

  def rating
    @start, @end = params[:rating].split("-")
    @films = Film.order('title ASC').joins(:screenings).merge(Screening.where("rating >= #{@start} AND rating <= #{@end}")).paginate(:page => params[:page], :per_page => 30)
    render :action => "index"
  end

  # GET /films/1
  # GET /films/1.json
  def show

    @screenings = @film.screenings.order('date ASC')

    if request.path != film_path(@film)
      redirect_to @film, status: :moved_permanently
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @film }
      end
    end
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)
    @directors = Director.where(:id => params[:directors])
    @film.directors << @directors

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render action: 'show', status: :created, location: @film }
      else
        format.html { render action: 'new' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    @directors = Director.where(:id => params[:directors])
    @film.directors.destroy_all
    @film.directors << @directors

    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:title, :year, :image, :director_ids => [])
    end
  end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_film.html.erb
<li<%= ' class="recent"'.html_safe if film.recently_seen? %>><b><%= link_to film.title, film %></b> (<%= film.year %>, <%= display_directors(film) %>) <span class="rating"><%=h film.last_rating %></span></li><%= "\r" %>

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field film_title__field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field film_year__field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>
  <div class="field film_directors__field">
    <%= f.label :directors %>
    <%= select_tag "directors", options_from_collection_for_select(Director.all, 'id', 'full_name',@film.directors.map{ |j| j.id }), :multiple => true, :size => 20, :class => 'chosen-select' %>
  </div>
  <div class="field image__field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <% if @film.image.exists? %>
    <div class="preview">
      <%= image_tag image_path(@film.image.url(:thumb)) %>
    </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/all.html.erb
<% title "JSON Experiment - Screening Log" %>




<script>

    var films = <%= raw @films.to_json %>;


    var collection = new PourOver.Collection(films);

    var year_filter = PourOver.makeExactFilter("year", 1999);

    collection.addFilters([year_filter]);

    console.log(collection);

</script>

app/views/films/decades.html.erb
<% title "Decades - Screening Log" %>

<div class="top-tens">
  <h1>Top Films by Decade</h1>
  <% @decades.sort.reverse.each do |decade, films|  %>
  <div class="year-list">
    <h2><%= decade %></h2>
    <ol>
     <%= render films[0..29] %>
   </ol>
 </div>
 <% end -%>

</div>

app/views/films/edit.html.erb
<% title "Editing #{@film.title} - Films - Screening Log" %>

<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<% title "Films - Screening Log" %>

<div class="films__index">

  <% if params[:search]  %>
  <h1>Search Results for &#8220;<%= params[:search] %>&#8221;</h1>
  <% else %>
  <h1>Films <small><%= @films.count %></small></h1>
  <% end %>

  <%= link_to 'New Film', new_film_path, :class => "button" %>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Year</th>
        <th>Director</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @films.each do |film| %>
      <tr>
        <td><%= link_to film.title, film %></td>
        <td><%= link_to film.year, "films/year/#{film.year}" %></td>
        <td><%= display_directors(film) %></td>
        <td><%= link_to edit_film_path(film), :class => 'action-link' do %><%= fa_icon "pencil" %><% end %></td>
        <td><%= link_to film, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'action-link' do %><%= fa_icon "times" %><% end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @films %>

</div>

app/views/films/new.html.erb
<% title "New - Films - Screening Log" %>

<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<% title "#{@film.title} - Films - Screening Log" %>

<article class="film">

  <% if notice %>
      <p class="notice"><%= notice %></p>
  <% end %>

  <div class="film__title-container">
  <h1 class="film__title"><%= @film.title %> (<%= link_to @film.year, "/films/year/#{@film.year}" %>, <%= display_directors(@film) %>)</h1>
  </div>

  <nav class="director-action-nav">
   <%= link_to edit_film_path(@film), :class => 'action-link' do %><%= fa_icon "pencil", text: "Edit" %><% end %> &nbsp;&nbsp;<%= link_to @film, method: :delete, data: { confirm: 'Are you sure?' }, class: 'action-link' do %><%= fa_icon "times", text: "Delete" %><% end %>&nbsp;&nbsp;<%#= link_to 'Back', films_path, class: 'action-link' %>
  </nav>

  <%= image_tag image_path(@film.image.url(:large)) if @film.image %>

  <div class="screenings">
    <%= link_to 'New Screening', "/screenings/new?id=#{@film.id}", :class => "button" %>
    <ol>
      <%- @screenings.each do |screening| -%>
      <li><%= link_to screening.date.strftime("%m/%d/%Y %I:%M %p"), screening %> <span>(<%= screening.rating %>)</span></li>
      <%- end -%>
    </ol>
  </div>

  <p>
    <%= link_to 'Back', films_path %>
  </p>


</article>

app/views/films/top100.html.erb
<% title "Top 250 - Screening Log" %>
<div class="top-100">
    <h1>Top 250</h1>

    <% if params[:type] == "grid" %>

    <%= link_to("List",top_100_path,:class => "button") %>

    <div class="top-100-grid">
        <%- @films.each do |film| -%>

        <div class="module">
           <%= link_to film do %>
            <%= image_tag image_path(film.image.url(:thumb))  %>
           <% end %>
       </div>

    <% end -%>
    </div>

   <% else %>

   <%= link_to("Grid",top_100_grid_path(type: "grid"), :class => "button") %>

   <ol>
    <%- @films.each do |film| -%>
        <%= render film %>
    <%- end -%>
    </ol>
    <% end %>
</div>

app/views/films/toptens.html.erb
<% title "Top Tens - Screening Log" %>

<div class="top-tens">
<h1>Top Tens</h1>
<%- @film_years.sort.reverse.each do |year, films| -%>
<div class="year-list">
   <h2><%= link_to year, year_path(year) %></h2>
   <ol>
      <%= render films[0..9] %>
   </ol>
   <%- honorable_mentions = films[10...-1] || 0 -%>
   <%- if honorable_mentions.size > 9 -%>
   <p class="honorable-mentions">
    <b>HONORABLE MENTION:</b>
    <%=  honorable_mentions.map{|film| content_tag(:b, link_to(film.title, film)) + " (" + display_directors(film) + ")"}.join(", ").html_safe  %>
   </p>
   <%- end -%>
</div>
<%- end -%>
</div>

app/views/films/year.html.erb
<% title "#{@year} - Films - Screening Log" %>


<div class  ="year-list">

  <h1>Film Year: <%= @year %> <small><%= @films.count %></small></h1>

  <% if params[:type] == "grid" %>

    <%= link_to "List", year_path(@year) %>

    <div class="module-container">

      <%- @films.each do |film| -%>

      <div class="module">
       <%= link_to film do %>
       <%= image_tag image_path(film.image.url(:thumb))  %>
       <% end %>

      <div class="module__info">
      <div class="inner-cell"><div class="center-cell">
        <%= link_to film.title, film, :class => "module__film-title" %>
        <span class="module__meta">(<%=h film.year %>, <%= display_directors(film) %>)<br>
          <span class="module__rating"><%=h film.last_rating %></span>
        </span></div>
      </div>
    </div>
     </div>


     <% end -%>

   </div>

   <nav class="year-nav">
    <% if @previous_year %>
    <%= link_to "&larr; #{@previous_year}".html_safe, year_grid_path(@previous_year,"grid") %>
    <% end %>
    <% if @next_year %>
    <%= link_to "#{@next_year} &rarr;".html_safe, year_grid_path(@next_year,"grid") %>
    <% end %>
  </nav>



  <% else %>

    <%= link_to "Grid", year_grid_path(@year,"grid") %>

    <% if @films.blank? %>
    <h2>No Films</h2>
    <% else %>
    <ol>
      <% @films.each do |film| %>
      <li<%= ' class="recent"'.html_safe if film.recently_seen? %>><b><%= link_to film.title, film %></b> (<%= display_directors(film) %>) <span class="rating"><%=h film.last_rating %></span></li>
      <% end %>
    </ol>
    <% end %>

    <nav class="year-nav">
      <% if @previous_year %>
      <%= link_to "&larr; #{@previous_year}".html_safe, year_path(@previous_year) %>
      <% end %>
      <% if @next_year %>
      <%= link_to "#{@next_year} &rarr;".html_safe, year_path(@next_year) %>
      <% end %>
    </nav>


  <% end %>





</div>