config/routes.rb
ScreeningLog::Application.routes.draw do
  resources :screenings
  resources :directors
  resources :films

  root 'screenings#recent'

  get 'screenings/year/:year' => 'screenings#year', as: 'screening_year'

  get 'films/year/:year' => 'films#year', as: 'year'
  get 'films-by-rating/:rating' => 'films#rating', as: 'rating'
  get 'films/year/:year/:type' => 'films#year', as: 'year_grid'
  get '/recent' => 'screenings#recent', as: 'recent'

  get '/search' => 'films#search'

  get '/top-tens' => 'films#toptens', as: 'top_tens'
  get '/decades' => 'films#decades', as: 'decades'
  get '/top-100' => 'films#top100', as: 'top_100'
  get '/worst' => 'films#worst', as: 'worst'
  get '/top-100/:type' => 'films#top100', as: 'top_100_grid'
  get '/no-directors' => 'films#no_directors', as: 'no_directors'

  get '/visualized' => 'screenings#visualized', as: 'visualized'

  get '/all' => "films#all", as: 'all'

  get '/no-images' => 'films#no_images', as: 'no_image'

end

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">

    <header class="global-header">
      <nav>
        <ul>
          <li><%= link_to("Films",films_path) %></li>
          <li><%= link_to("Directors",directors_path) %></li>
          <li>
            <%= link_to("Screenings",screenings_path) %> &nbsp;
            (<%= link_to("2018", "/screenings/year/2018") %>)
          </li>
          <li><%= link_to("Top Tens",top_tens_path) %></li>
          <li><%= link_to("Top 250",top_100_path) %></li>
          <li><%= link_to("Visualized",visualized_path) %></li>
          <li><%= link_to("Recent",recent_path) %></li>
        </ul>
      </nav>

      <div class="search">
        <%= form_tag("/search", method: "get") do %>
        <input type="text" name="search" value="<%= params[:search] %>" id="search" placeholder="Search Films">
        <% end %>
        <%#= fa_icon "search" %>
      </div>

    </header>

    <%= yield %>
  </div>

</body>
</html>